version: 0.2

env:
  variables:
    AUTH_TOKEN: my-super-secret-static-token

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running unit tests with SQLite..."
      - pytest tests/test.py -v --tb=short
      - echo "Tests completed successfully!"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Generating deployment artifact..."

artifacts:
  name: dev-for-fun-ci-${CODEBUILD_BUILD_NUMBER}.zip
  files:
    - '**/*'
  exclude-paths:
    - venv/**/*
    - .git/**/*
    - tests/**/*
    - .env
    - __pycache__/**/*
    - '**/*.pyc'
    - .ebextensions/**/*
    - postgres_data/**/*
    - pytest_cache/**/*
