version: 0.2

env:
  variables:
    RDS_HOSTNAME: localhost
    RDS_PORT: 5432
    RDS_USERNAME: postgres
    RDS_PASSWORD: postgres
    RDS_DB_NAME: blacklistdb
    AUTH_TOKEN: my-super-secret-static-token

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Starting PostgreSQL Docker container..."
      - docker run -d --name test-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=blacklistdb -p 5432:5432 postgres:15-alpine

      - echo "Installing PostgreSQL client..."
      - apt-get update && apt-get install -y postgresql-client

      - echo "Waiting for PostgreSQL to be ready..."
      - |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL ($i/30)..."
          sleep 2
        done
      - echo "Database service is available for migrations/tests!"

  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/test.py -v --tb=short
      - echo "Tests completed successfully!"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Generating deployment artifact..."

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - venv/**/*
    - .git/**/*
    - tests/**/*
    - .env
    - __pycache__/**/*
    - '**/*.pyc'
    - .ebextensions/**/*
    - postgres_data/**/*
